services:
  # Jaeger
  jaeger:
    container_name: jaeger
    image: jaegertracing/jaeger:latest
    networks:
      monitoring:
        # This is the host name used in Prometheus scrape configuration.
        aliases: [spm_metrics_source]
    volumes:
      - "./jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
      - "./config-spm.yaml:/etc/jaeger/config.yml"
    command: ["--config", "/etc/jaeger/config.yml"]
    ports:
      - "16686:16686"   # UI
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP
      - "8888:8888"     # Metrics
      - "8889:8889"     # Metrics
      - "14269:14269"   # Health

  # Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    networks:
      - monitoring
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

networks:
  monitoring:
    driver: bridge
